# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  paths:
    exclude:
    - README.md

# trigger target branch
pr:
  branches:
    include:
    - master
    - develop

resources:
- repo: self

variables:
  keySendGrid: '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'

stages:
- stage: Deploy
  displayName: Deploy to slot
  jobs:
  - job: Deploy
    displayName: Deploy job
    steps:
    - task: SendGridEmail@2
      inputs:
        SendGridApiKey: '$(keySendGrid)'
        FromAddress: 'Duy Tran <duyquang130@gmail.com>'
        ToAddresses: 'Duy Tran <duyquangtran@kms-technology.com>'
        Subject: '$(Build.DefinitionNam) Finished Successfully'
        emailBodyFormat: 'InLine'
        EmailBody: 'Deploy Success'