# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include: 
    - master
  paths:
    exclude:
    - README.md

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'onlylight291998/docker_dotnet'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Azure DevOps'
        KeyVaultName: 'kvault-demo-12'
        SecretsFilter: '*'
        RunAsPreJob: false
    - task: Docker@2
      inputs:
        containerRegistry: 'Onlylight Docker Hub'
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to slot
  jobs:
  - job: Deploy
    displayName: Deploy job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure DevOps'
        appType: 'webAppContainer'
        WebAppName: 'blazordemo123'
        DockerNamespace: 'registry-1.docker.io'
        DockerRepository: '$(imageRepository)'
        DockerImageTag: '$(tag)'
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'Azure DevOps'
        Action: 'Enable Continuous Monitoring'
        WebAppName: 'blazordemo123'
        SpecifySlotOrASE: true
        ResourceGroupName: 'demo-rg'
        Slot: 'production'
        AppInsightsResourceGroupName: 'demo-rg'
        ApplicationInsightsResourceName: 'Test Insights'
        ApplicationInsightsWebTestName: 'Test Insights'