# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  paths:
    exclude:
    - README.md

# trigger target branch
pr:
  branches:
    include:
    - master
    - develop

resources:
- repo: self

stages:
- stage: Deploy
  displayName: Deploy to slot
  jobs:
  - job: Deploy
    displayName: Deploy job
    steps:
    - task: SendGridEmail@2
      inputs:
        SendGridApiKey: '$(SendGridKey)'
        FromAddress: 'Duy Tran <duyquang130@gmail.com>'
        ToAddresses: 'Duy Tran <duyquangtran@kms-technology.com>, Duy Tran <duyquang130@gmail.com>'
        Subject: '$(Build.DefinitionName) Finished Successfully'
        emailBodyFormat: 'InLine'
        EmailBody: '<h4>SourceBranch $(System.PullRequest.SourceBranch)</h4><h4>TargetBranch $(System.PullRequest.TargetBranch)</h4><h4>SourceVersionMessage $(Build.SourceVersionMessage)</h4><h4>URI $(System.PullRequest.SourceRepositoryURI)</h4>'
        sendAsHtml: true